---
title: Welcome to my online CS Journey!
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mabarrera@csumb.edu
description: Theme descritions
baseurl: 
url: https://MarcosBSD.github.io
title_description: Title Description
title_image: "/uploads/cropped-tunnel.jpg"
google_analytics: UA-163962122-1
disqus_account: 
github_repository: https://github.com/MarcosBSD
addthis_id: 
post_limit: 5
twitter_username: 
github_username: MarcosBSD
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link: 
facebook_link: 
footer_left: Made with <i class="fa fa-heart"></i> by <a href="https://twitter.com/_JacobTomlinson">Jacob
  Tomlinson</a>
footer_right: '&lt;/&gt; on <a href="https://github.com/jacobtomlinson/carte-noire">Github</a>
  &nbsp;<i class="fa fa-github-alt"></i>'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
- vendor
